apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-weights-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      # EFS is elastic and ignores this number, but Kubernetes requires a value.
      storage: 300Gi
