apiVersion: v1
kind: Service
metadata:
  name: ocr-vlm-lb-service
  namespace: default
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: ocr-vlm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
